# Generated by Django 4.2.5 on 2023-11-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_type_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('new_friendrequest', 'New friendrequest'), ('post_comment', 'Post comment'), ('post_like', 'Post like'), ('rejected_friendrequest', 'Rejected friendrequest'), ('accepted_friendrequest', 'Accepted friendrequest')], max_length=50),
        ),
    ]
